version: '3.9'

networks:
  rat_net:

services:
  django:
    build: .
    command: "gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi"
    volumes:
      - static_data:/static
    ports:
      - "8000:8000"
    networks:
      - rat_net
  nginx:
    image: nginx:latest
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/static
      - ./nginx-conf.d:/etc/nginx/conf.d
    networks:
      - rat_net
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - rat_net
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django
volumes:
  postgres_data:
  static_data:
    